stages:
  - test

variables:
  DOCKER_VERSION: stable

unittest:
  stage: test
  image: maven:3.8.4-openjdk-17-slim
  script:
    - mvn -f app/movie-uploader/pom.xml verify
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - "app/**/*"
