name: Terraform Plan

on:
  pull_request:
    branches:
      - main

jobs:
  plan:
    name: Plan
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    env:
      AWS_REGION: ap-northeast-1
      TF_IN_AUTOMATION: true

    strategy:
      matrix:
        dir:
          - aws/backend
          - aws/budgets
          - aws/memories
          - aws/github_actions
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # matrix.dir で指定されたサブディレクトリの中にある terraform ファイルの差分を確認する
      - name: Diff Terraform Scripts
        id: diff
        uses: technote-space/get-diff-action@v5
        with:
          PATTERNS: |
            ${{ matrix.dir }}/**/*.tf
            ${{ matrix.dir }}/**/*.tfvars

      - name: Configure aws credentials
        if: steps.diff.outputs.diff
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.TERRAFORM_ROLE_TO_ASSUME }}
          role-duration-seconds: 900
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup terraform
        if: steps.diff.outputs.diff
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.10
          terraform_wrapper: true

      - name: Check format
        id: fmt
        if: steps.diff.outputs.diff
        run: terraform fmt -check -recursive
        working-directory: ${{ matrix.dir }}
        continue-on-error: true

      - name: Comment format results
        uses: robburger/terraform-pr-commenter@v1
        if: steps.fmt.outputs.diff
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commenter_type: fmt
          commenter_input: ${{ format('{0}{1}', steps.fmt.outputs.stdout, steps.fmt.outputs.stderr) }}
          commenter_exitcode: ${{ steps.fmt.outputs.exitcode }}

      - name: Initialize
        id: init
        if: steps.diff.outputs.diff
        run: terraform init
        working-directory: ${{ matrix.dir }}

      - name: Comment initialization results
        uses: robburger/terraform-pr-commenter@v1
        if: steps.init.outputs.diff
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commenter_type: init
          commenter_input: ${{ format('{0}{1}', steps.init.outputs.stdout, steps.init.outputs.stderr) }}
          commenter_exitcode: ${{ steps.init.outputs.exitcode }}

      - name: Validate
        id: validate
        if: steps.diff.outputs.diff
        run: terraform validate -no-color
        working-directory: ${{ matrix.dir }}

      - name: Comment validate results
        uses: robburger/terraform-pr-commenter@v1
        if: steps.validate.outputs.diff
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commenter_type: validate
          commenter_input: ${{ format('{0}{1}', steps.validate.outputs.stdout, steps.validate.outputs.stderr) }}
          commenter_exitcode: ${{ steps.validate.outputs.exitcode }}

      - name: Plan
        if: steps.diff.outputs.diff
        id: plan
        run: terraform plan -no-color
        working-directory: ${{ matrix.dir }}
        continue-on-error: true

      - name: Comment plan results
        uses: robburger/terraform-pr-commenter@v1
        if: steps.diff.outputs.diff
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commenter_type: plan # Choose one
          commenter_input: ${{ format('{0}{1}', steps.plan.outputs.stdout, steps.plan.outputs.stderr) }}
          commenter_exitcode: ${{ steps.plan.outputs.exitcode }}

      - name: Exit with appropriate status
        if: steps.fmt.outcome == 'failure' || steps.init.outcome == 'failure' || steps.validate.outcome == 'failure' || steps.plan.outcome == 'failure'
        run: exit 1
